import type { Metadata } from "next";
import { Geist, Chango } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import Logo from "@/components/logo";
import { TopBar } from "@/components/top-bar";
import { CartProvider } from "@/features/cart/context/cart-context";
import CartIcon from "@/features/cart/components/cart-icon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const chango = Chango({
  variable: "--font-chango",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${chango.variable} antialiased  text-[#3e443d]`}
      >
        <CartProvider>
          <div className="bg-[#eff0ef]">
            <TopBar />
            <div className="max-w-7xl mx-auto pt-3 pr-6">
              <div className="flex items-center justify-between">
                <Logo />
                <CartIcon />
              </div>
              <Navbar />
            </div>
          </div>
          <div className="">{children}</div>
        </CartProvider>
      </body>
    </html>
  );
}
