import type { Metadata } from "next";
import { Geist, Geist_Mono, Chango} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";

import Logo from "@/components/logo";
import { TopBar } from "@/components/top-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const chango = Chango({
  variable: "--font-chango",
  subsets: ["latin"],
weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${chango.variable} antialiased  text-[#3e443d]`}
      >
        <div className="bg-[#eff0ef]">
          <TopBar />
        <div className="flex justify-between pt-3 max-w-7xl mx-auto">
          <div>

          <Logo />
          <Navbar />
          </div>
        </div>
        </div>
        <div className="">
        {children}
        </div>
      </body>
    </html>
  );
}
